stages:
  - setup

variables:
  REPO_URL: "ssh://git@gitlab.webexpertsnepal.com:2020/sabin/react-test-app.git"  # Default repository URL 
  PROJECT_NAME: node_app # Use the GitLab project name as the folder name 
  GIT_HUB_REPO: "webexpertsnepal13/react-test.git"
  PORT: "3005"  # Replace with a dynamic port for each project

setup:
  stage: setup
  script:
    - bash /home/gitlab-runner/reactProjects.sh $PROJECT_NAME $REPO_URL $GIT_HUB_REPO $PORT  # Run the script with project name and repo URL
  only:
    - main  # Specify which branch to trigger the pipeline on
